#!/bin/sh

rm -R build
rm -R dist
rm *.spec

./venv/bin/pyinstaller indicator.py \
    --name 'fortivpn-quick-tray' \
    --onefile \
    --noconsole \
    --noconfirm \
    --clean \
    --add-data './icons/*.png:icons' \
    --exclude-module 'PySide2.QtQml' \
    --exclude-module 'PySide2.QtNetwork'